/**
 * The token format, on its own.
 *
 * Parsing is where a credential system usually gets lenient, and leniency here
 * is not a convenience — it is an accepted shape. A parser that trims
 * whitespace accepts a token that was pasted with a newline; one that ignores
 * a trailing segment accepts a token somebody appended to. Both then have to
 * be matched by whatever stores and compares them, and the shapes multiply.
 *
 * So the parser is anchored and total: a string is the token or it is not.
 *
 * Nothing here is a real credential. Tokens are generated by the code under
 * test, and no fixed example is written down — an example in a source file is
 * a string somebody will eventually paste somewhere real.
 */

import { describe, expect, it } from 'vitest';

import {
  formatCredentialToken,
  generateCredentialToken,
  hashCredentialSecret,
  InvalidCredentialTokenError,
  LOOKUP_LENGTH,
  parseCredentialToken,
  SECRET_LENGTH,
  TOKEN_PREFIX,
} from '../../src/domain/credential.js';

const BASE64URL = /^[A-Za-z0-9_-]+$/;

describe('a generated token', () => {
  it('has the two halves the format promises', () => {
    const token = generateCredentialToken();

    expect(token.lookup).toHaveLength(LOOKUP_LENGTH);
    expect(token.secret).toHaveLength(SECRET_LENGTH);
    expect(token.lookup).toMatch(BASE64URL);
    expect(token.secret).toMatch(BASE64URL);
  });

  it('renders as prefix, lookup and secret', () => {
    const token = generateCredentialToken();

    expect(formatCredentialToken(token)).toBe(`${TOKEN_PREFIX}_${token.lookup}_${token.secret}`);
  });

  it('is different every time', () => {
    // Not a randomness test — a smoke check that nothing is memoised. A
    // credential that repeats is one credential.
    const tokens = Array.from({ length: 50 }, () =>
      formatCredentialToken(generateCredentialToken()),
    );

    expect(new Set(tokens).size).toBe(50);
  });

  it('survives a round trip', () => {
    const token = generateCredentialToken();

    expect(parseCredentialToken(formatCredentialToken(token))).toEqual(token);
  });
});

describe('what the parser refuses', () => {
  const valid = generateCredentialToken();
  const rendered = formatCredentialToken(valid);

  it.each([
    ['an empty string', ''],
    ['only the prefix', TOKEN_PREFIX],
    ['a prefix and a lookup', `${TOKEN_PREFIX}_${valid.lookup}`],
    ['the wrong prefix', `key_${valid.lookup}_${valid.secret}`],
    ['no prefix at all', `${valid.lookup}_${valid.secret}`],
    ['a lookup one character short', `${TOKEN_PREFIX}_${valid.lookup.slice(1)}_${valid.secret}`],
    ['a lookup one character long', `${TOKEN_PREFIX}_a${valid.lookup}_${valid.secret}`],
    ['a secret one character short', `${TOKEN_PREFIX}_${valid.lookup}_${valid.secret.slice(1)}`],
    ['a secret one character long', `${TOKEN_PREFIX}_${valid.lookup}_a${valid.secret}`],
    [
      'an illegal character in the lookup',
      `${TOKEN_PREFIX}_${'!'.padEnd(LOOKUP_LENGTH, 'a')}_${valid.secret}`,
    ],
    [
      'an illegal character in the secret',
      `${TOKEN_PREFIX}_${valid.lookup}_${'!'.padEnd(SECRET_LENGTH, 'a')}`,
    ],
    ['leading whitespace', ` ${rendered}`],
    ['trailing whitespace', `${rendered} `],
    ['a trailing newline', `${rendered}\n`],
    ['an extra segment', `${rendered}_extra`],
    ['a leading segment', `x_${rendered}`],
    ['the halves swapped', `${TOKEN_PREFIX}_${valid.secret}_${valid.lookup}`],
    ['an uppercase prefix', `MEM_${valid.lookup}_${valid.secret}`],
  ])('refuses %s', (_label, presented) => {
    // Anything lenient here becomes a second accepted shape, and every shape
    // has to be handled identically by everything downstream.
    expect(() => parseCredentialToken(presented)).toThrow(InvalidCredentialTokenError);
  });

  it('says nothing about what was wrong', () => {
    const secret = generateCredentialToken().secret;

    try {
      parseCredentialToken(`${TOKEN_PREFIX}_short_${secret}`);
      expect.unreachable('the parser should have refused');
    } catch (error) {
      const refused = error as Error;
      // Naming the failing part would narrow a guess, and the string it would
      // be describing is a credential somebody typed.
      expect(refused.message).not.toContain(secret);
      expect(JSON.stringify(refused)).not.toContain(secret);
      expect(refused.stack ?? '').not.toContain(secret);
    }
  });
});

describe('the digest a row keeps', () => {
  it('is thirty-two bytes, as the column requires', () => {
    expect(hashCredentialSecret(generateCredentialToken().secret)).toHaveLength(32);
  });

  it('is the same for the same secret and different for another', () => {
    const first = generateCredentialToken().secret;
    const second = generateCredentialToken().secret;

    expect(hashCredentialSecret(first).equals(hashCredentialSecret(first))).toBe(true);
    expect(hashCredentialSecret(first).equals(hashCredentialSecret(second))).toBe(false);
  });

  it('cannot be read back as the secret', () => {
    const secret = generateCredentialToken().secret;

    // Stating the obvious on purpose: this is the property the whole scheme
    // rests on, and the digest is what a database dump would contain.
    const digest = hashCredentialSecret(secret);
    expect(digest.toString('utf8')).not.toContain(secret);
    expect(digest.toString('base64url')).not.toContain(secret);
    expect(digest.toString('hex')).not.toContain(secret);
  });
});
