/**
 * The token format, on its own.
 *
 * Parsing is where a credential system usually gets lenient, and leniency here
 * is not a convenience — it is an accepted shape. A parser that trims
 * whitespace accepts a token that was pasted with a newline; one that ignores
 * a trailing segment accepts a token somebody appended to. Both then have to
 * be matched by whatever stores and compares them, and the shapes multiply.
 *
 * So the parser is anchored and total: a string is the token or it is not.
 *
 * The halves are separated by a dot rather than an underscore, and the tests
 * that matter most here are the ones that prove why. An underscore is a legal
 * base64url character, so the old grammar accepted some *swapped* renderings —
 * whenever the secret happened to carry an underscore where the lengths could
 * re-align. Those cases are constructed deliberately below rather than waited
 * for: a corruption that is refused one time in sixty-four is not refused.
 *
 * Nothing here is a real credential. Tokens are generated by the code under
 * test, and no fixed example is written down — an example in a source file is
 * a string somebody will eventually paste somewhere real.
 */

import { describe, expect, it } from 'vitest';

import {
  formatCredentialToken,
  generateCredentialToken,
  hashCredentialSecret,
  InvalidCredentialTokenError,
  LOOKUP_LENGTH,
  parseCredentialToken,
  SECRET_LENGTH,
  TOKEN_PREFIX,
} from '../../src/domain/credential.js';

const BASE64URL = /^[A-Za-z0-9_-]+$/;

describe('a generated token', () => {
  it('has the two halves the format promises', () => {
    const token = generateCredentialToken();

    expect(token.lookup).toHaveLength(LOOKUP_LENGTH);
    expect(token.secret).toHaveLength(SECRET_LENGTH);
    expect(token.lookup).toMatch(BASE64URL);
    expect(token.secret).toMatch(BASE64URL);
  });

  it('renders as prefix, lookup and secret', () => {
    const token = generateCredentialToken();

    expect(formatCredentialToken(token)).toBe(`${TOKEN_PREFIX}_${token.lookup}.${token.secret}`);
  });

  it('is different every time', () => {
    // Not a randomness test — a smoke check that nothing is memoised. A
    // credential that repeats is one credential.
    const tokens = Array.from({ length: 50 }, () =>
      formatCredentialToken(generateCredentialToken()),
    );

    expect(new Set(tokens).size).toBe(50);
  });

  it('survives a round trip', () => {
    const token = generateCredentialToken();

    expect(parseCredentialToken(formatCredentialToken(token))).toEqual(token);
  });
});

describe('what the parser refuses', () => {
  const valid = generateCredentialToken();
  const rendered = formatCredentialToken(valid);

  it.each([
    ['an empty string', ''],
    ['only the prefix', TOKEN_PREFIX],
    ['a prefix and a lookup', `${TOKEN_PREFIX}_${valid.lookup}`],
    ['the wrong prefix', `key_${valid.lookup}_${valid.secret}`],
    ['no prefix at all', `${valid.lookup}_${valid.secret}`],
    ['a lookup one character short', `${TOKEN_PREFIX}_${valid.lookup.slice(1)}_${valid.secret}`],
    ['a lookup one character long', `${TOKEN_PREFIX}_a${valid.lookup}_${valid.secret}`],
    ['a secret one character short', `${TOKEN_PREFIX}_${valid.lookup}_${valid.secret.slice(1)}`],
    ['a secret one character long', `${TOKEN_PREFIX}_${valid.lookup}_a${valid.secret}`],
    [
      'an illegal character in the lookup',
      `${TOKEN_PREFIX}_${'!'.padEnd(LOOKUP_LENGTH, 'a')}_${valid.secret}`,
    ],
    [
      'an illegal character in the secret',
      `${TOKEN_PREFIX}_${valid.lookup}_${'!'.padEnd(SECRET_LENGTH, 'a')}`,
    ],
    ['leading whitespace', ` ${rendered}`],
    ['trailing whitespace', `${rendered} `],
    ['a trailing newline', `${rendered}\n`],
    ['an extra segment', `${rendered}_extra`],
    ['a leading segment', `x_${rendered}`],
    ['the halves swapped', `${TOKEN_PREFIX}_${valid.secret}_${valid.lookup}`],
    ['an uppercase prefix', `MEM_${valid.lookup}_${valid.secret}`],
  ])('refuses %s', (_label, presented) => {
    // Anything lenient here becomes a second accepted shape, and every shape
    // has to be handled identically by everything downstream.
    expect(() => parseCredentialToken(presented)).toThrow(InvalidCredentialTokenError);
  });

  it('says nothing about what was wrong', () => {
    const secret = generateCredentialToken().secret;

    try {
      parseCredentialToken(`${TOKEN_PREFIX}_short_${secret}`);
      expect.unreachable('the parser should have refused');
    } catch (error) {
      const refused = error as Error;
      // Naming the failing part would narrow a guess, and the string it would
      // be describing is a credential somebody typed.
      expect(refused.message).not.toContain(secret);
      expect(JSON.stringify(refused)).not.toContain(secret);
      expect(refused.stack ?? '').not.toContain(secret);
    }
  });
});

describe('the digest a row keeps', () => {
  it('is thirty-two bytes, as the column requires', () => {
    expect(hashCredentialSecret(generateCredentialToken().secret)).toHaveLength(32);
  });

  it('is the same for the same secret and different for another', () => {
    const first = generateCredentialToken().secret;
    const second = generateCredentialToken().secret;

    expect(hashCredentialSecret(first).equals(hashCredentialSecret(first))).toBe(true);
    expect(hashCredentialSecret(first).equals(hashCredentialSecret(second))).toBe(false);
  });

  it('cannot be read back as the secret', () => {
    const secret = generateCredentialToken().secret;

    // Stating the obvious on purpose: this is the property the whole scheme
    // rests on, and the digest is what a database dump would contain.
    const digest = hashCredentialSecret(secret);
    expect(digest.toString('utf8')).not.toContain(secret);
    expect(digest.toString('base64url')).not.toContain(secret);
    expect(digest.toString('hex')).not.toContain(secret);
  });
});

describe('the delimiter, and what it makes impossible', () => {
  /**
   * Halves built by hand, so the interesting case is certain rather than
   * likely.
   *
   * The secret carries an underscore at index 16 deliberately: that is the
   * exact position at which the old grammar re-aligned, and it is what made a
   * swapped token parse. Nothing here is a credential — the characters are
   * repeated filler, and no complete usable example is written down.
   */
  const lookup = 'a'.repeat(LOOKUP_LENGTH);
  const secret = `${'b'.repeat(16)}_${'c'.repeat(26)}`;

  it('uses halves of the lengths the format promises', () => {
    // Asserted first, because every refusal below is only meaningful if these
    // stand in for real halves.
    expect(lookup).toHaveLength(LOOKUP_LENGTH);
    expect(secret).toHaveLength(SECRET_LENGTH);
    expect(secret[16]).toBe('_');
  });

  it('refuses the halves swapped, whatever the secret contains', () => {
    // The whole point. A swap cannot satisfy 16 then 43 when the delimiter
    // cannot occur inside either half, so this is refused by construction
    // rather than by luck.
    expect(() => parseCredentialToken(`${TOKEN_PREFIX}_${secret}.${lookup}`)).toThrow(
      InvalidCredentialTokenError,
    );
  });

  it('refuses an ordinary token in the previous rendering', () => {
    // Deliberate: the old grammar is not accepted alongside the new one. Every
    // string it accepted included some its own swaps, so keeping it would keep
    // the ambiguity.
    expect(() => parseCredentialToken(`${TOKEN_PREFIX}_${lookup}_${secret}`)).toThrow(
      InvalidCredentialTokenError,
    );
  });

  it('refuses the specimen the previous rendering used to accept', () => {
    // This exact string parsed under the old grammar: the underscore at index
    // 16 of the secret let the lengths re-align, yielding a lookup and a secret
    // that were never issued together.
    expect(() => parseCredentialToken(`${TOKEN_PREFIX}_${secret}_${lookup}`)).toThrow(
      InvalidCredentialTokenError,
    );
  });

  it.each([
    ['two delimiters between the halves', `${TOKEN_PREFIX}_${lookup}..${secret}`],
    ['a further segment appended', `${TOKEN_PREFIX}_${lookup}.${secret}.extra`],
    ['a delimiter inside the lookup', `${TOKEN_PREFIX}_${'a'.repeat(15)}..${secret}`],
    ['a delimiter inside the secret', `${TOKEN_PREFIX}_${lookup}.${'c'.repeat(42)}.`],
    ['no delimiter at all', `${TOKEN_PREFIX}_${lookup}${secret}`],
  ])('refuses %s', (_label, presented) => {
    expect(() => parseCredentialToken(presented)).toThrow(InvalidCredentialTokenError);
  });

  it('says nothing about which part was wrong', () => {
    // A token that failed to parse is still somebody's credential. Naming the
    // half, the position or the expected shape would both narrow a guess and
    // put the value one careless line away from a log.
    const raised = (() => {
      try {
        parseCredentialToken(`${TOKEN_PREFIX}_${secret}.${lookup}`);
        return undefined;
      } catch (error) {
        return error;
      }
    })();

    expect(raised).toBeInstanceOf(InvalidCredentialTokenError);
    expect((raised as Error).message).toBe('Not a Memory credential token.');
    for (const leaked of [lookup, secret, 'delimiter', 'legacy', '16', '43']) {
      expect(`message names ${leaked}:${(raised as Error).message.includes(leaked)}`).toBe(
        `message names ${leaked}:false`,
      );
    }
  });
});
