/**
 * One sweep: find what needs generating, hand it to the scheduler, report
 * counts.
 *
 * This is the whole of the reconciliation primitive, and its smallness is the
 * design. It owns no timer — composition decides whether it runs at startup,
 * on an interval, after a provider recovers, or all three, and a timer buried
 * here would run even in compositions that have no provider to run for. It
 * owns no generation — the coordinator does, with its single-flight and its
 * bound. It deletes nothing — a soft-outdated artifact keeps serving until
 * the regeneration's locked gate replaces it, and a hard-incompatible one is
 * already invisible to every reader.
 *
 * The report is counts of a closed reason set and nothing else: no Problem
 * ids, no text, nothing a log line could leak. What an operator learns is
 * how much work a sweep found and of which kinds, which is also exactly what
 * a test asserts.
 */

import type { RetrievalArtifactReconciliationReader } from '../repository/retrieval-artifact-reconciliation-reader.js';
import type { RetrievalGenerationProfile } from '../domain/retrieval-generation-profile.js';
import { requireRetrievalGenerationProfile } from '../domain/retrieval-generation-profile.js';
import type { RetrievalGenerationRequests } from './retrieval-generation-coordinator.js';

/** What one sweep found, by kind, and how many requests it made. */
export interface RetrievalReconciliationReport {
  /** Problems handed to the scheduler. The sum of the three below. */
  readonly requested: number;
  /** No artifact at all: new, invalidated, or failed and not yet retried. */
  readonly artifactMissing: number;
  /** Fingerprinted under a source schema the readers no longer accept. */
  readonly sourceSchemaIncompatible: number;
  /** Generated by a stack that is no longer the configured one. */
  readonly generationProfileOutdated: number;
}

export interface RetrievalArtifactReconciliationService {
  /**
   * Runs one bounded sweep.
   *
   * An up-to-date store reports all zeros and will have made no request and
   * no provider call — the property that makes running this often safe. A
   * larger backlog than the scan bound drains across successive sweeps.
   */
  reconcile(): Promise<RetrievalReconciliationReport>;
}

/**
 * Builds the service around a reader, a scheduler and the configured profile.
 *
 * The profile arrives here rather than being discovered, because "what stack
 * is current" is configuration: the composition edge that chose the concrete
 * generator and embedding provider says so once, and this service compares
 * the store against what it was told.
 */
export function createRetrievalArtifactReconciliationService(
  reader: RetrievalArtifactReconciliationReader,
  requests: RetrievalGenerationRequests,
  profile: RetrievalGenerationProfile,
): RetrievalArtifactReconciliationService {
  const expected = requireRetrievalGenerationProfile(profile);

  return {
    async reconcile(): Promise<RetrievalReconciliationReport> {
      const findings = await reader.findProblemsNeedingGeneration(expected);

      let artifactMissing = 0;
      let sourceSchemaIncompatible = 0;
      let generationProfileOutdated = 0;

      for (const finding of findings) {
        switch (finding.reason) {
          case 'ARTIFACT_MISSING':
            artifactMissing += 1;
            break;
          case 'SOURCE_SCHEMA_INCOMPATIBLE':
            sourceSchemaIncompatible += 1;
            break;
          case 'GENERATION_PROFILE_OUTDATED':
            generationProfileOutdated += 1;
            break;
        }
        // Best-effort by contract: request neither throws nor waits, and a
        // request the coordinator coalesces away was still counted here —
        // the report says what the sweep found, not what ran.
        requests.request(finding.problemId);
      }

      return {
        requested: findings.length,
        artifactMissing,
        sourceSchemaIncompatible,
        generationProfileOutdated,
      };
    },
  };
}
